image: node:18.16.1

cache:
  paths:
    - node_modules/

stages:
  - build
  - tests
  - deploy

build-job:
  stage: build
  script:
    - echo "Compilation du code..."
    - npm install
    - echo "Compilation terminée"

unit-tests-job:
  stage: tests
  script:
    - echo "Lancement des tests unitaires...cela prendra 60secondes"
    - npm install
    - npm run test
    - echo "La couverture de code est de 90%"
  
deploy-job:
  stage: deploy
  image: ruby:latest
  script:
    - echo "Déploiement de l'application..."
    - curl -s "https://api.render.com/deploy/srv-${DEPLOY_HOOK_01}?key=${DEPLOY_HOOK_02}" -o file
  environment:
    name: production
    url: https://dashboard.render.com/web/srv-${DEPLOY_HOOK_01}
  only:
    - main